-- MySQL Script generated by MySQL Workbench
-- Tue Aug 10 15:17:30 2021
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`User`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`User` (
  `idUser` INT NOT NULL AUTO_INCREMENT,
  `Name` VARCHAR(45) NULL,
  `Password` VARCHAR(45) NULL,
  `create_time` DATETIME NULL DEFAULT CURRENT_TIMESTAMP,
  `Usercol` VARCHAR(45) NULL,
  PRIMARY KEY (`idUser`),
  UNIQUE INDEX `idUser_UNIQUE` (`idUser` ASC) VISIBLE,
  UNIQUE INDEX `Name_UNIQUE` (`Name` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Page`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Page` (
  `idPage` INT NOT NULL AUTO_INCREMENT,
  `Name` VARCHAR(45) NOT NULL,
  `user` VARCHAR(45) NOT NULL,
  `User_idUser` INT NOT NULL,
  PRIMARY KEY (`idPage`),
  INDEX `fk_Page_User_idx` (`User_idUser` ASC) VISIBLE,
  CONSTRAINT `fk_Page_User`
    FOREIGN KEY (`User_idUser`)
    REFERENCES `mydb`.`User` (`idUser`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`PageTextHistory`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`PageTextHistory` (
  `idPageText` INT NOT NULL AUTO_INCREMENT,
  `create_time` VARCHAR(45) GENERATED ALWAYS AS (current_timestamp) VIRTUAL,
  `Text` TEXT NULL,
  `User_idUser` INT NOT NULL,
  `Page_idPage` INT NOT NULL,
  PRIMARY KEY (`idPageText`),
  INDEX `fk_PageTextHistory_User1_idx` (`User_idUser` ASC) VISIBLE,
  INDEX `fk_PageTextHistory_Page1_idx` (`Page_idPage` ASC) VISIBLE,
  CONSTRAINT `fk_PageTextHistory_User1`
    FOREIGN KEY (`User_idUser`)
    REFERENCES `mydb`.`User` (`idUser`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_PageTextHistory_Page1`
    FOREIGN KEY (`Page_idPage`)
    REFERENCES `mydb`.`Page` (`idPage`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Vote_page`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Vote_page` (
  `idVotes` INT NOT NULL AUTO_INCREMENT,
  `Score` TINYINT NOT NULL,
  `create_time` DATETIME GENERATED ALWAYS AS (current_timestamp) VIRTUAL,
  `User_idUser` INT NOT NULL,
  `Page_idPage` INT NOT NULL,
  PRIMARY KEY (`idVotes`),
  INDEX `fk_Votes_User1_idx` (`User_idUser` ASC) VISIBLE,
  INDEX `fk_Vote_page_Page1_idx` (`Page_idPage` ASC) VISIBLE,
  CONSTRAINT `fk_Votes_User1`
    FOREIGN KEY (`User_idUser`)
    REFERENCES `mydb`.`User` (`idUser`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Vote_page_Page1`
    FOREIGN KEY (`Page_idPage`)
    REFERENCES `mydb`.`Page` (`idPage`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Vote_history`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Vote_history` (
  `idVotes` INT NOT NULL AUTO_INCREMENT,
  `Score` TINYINT NOT NULL,
  `create_time` DATETIME GENERATED ALWAYS AS (current_timestamp) VIRTUAL,
  `User_idUser` INT NOT NULL,
  `PageTextHistory_idPageText` INT NOT NULL,
  PRIMARY KEY (`idVotes`),
  INDEX `fk_Votes_User1_idx` (`User_idUser` ASC) VISIBLE,
  INDEX `fk_Vote_page_copy1_PageTextHistory1_idx` (`PageTextHistory_idPageText` ASC) VISIBLE,
  CONSTRAINT `fk_Votes_User10`
    FOREIGN KEY (`User_idUser`)
    REFERENCES `mydb`.`User` (`idUser`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Vote_page_copy1_PageTextHistory1`
    FOREIGN KEY (`PageTextHistory_idPageText`)
    REFERENCES `mydb`.`PageTextHistory` (`idPageText`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Options`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Options` (
  `idOptions` INT NOT NULL,
  `Page_idPage` INT NOT NULL,
  `Page_idPageTarget` INT NOT NULL,
  `Text` VARCHAR(45) NULL,
  `create_time` DATETIME GENERATED ALWAYS AS (CURRENT_TIMESTAMP) VIRTUAL,
  PRIMARY KEY (`idOptions`),
  UNIQUE INDEX `idOptions_UNIQUE` (`idOptions` ASC) VISIBLE,
  INDEX `fk_Options_Page1_idx` (`Page_idPage` ASC) VISIBLE,
  INDEX `fk_Options_Page2_idx` (`Page_idPageTarget` ASC) VISIBLE,
  CONSTRAINT `fk_Options_Page1`
    FOREIGN KEY (`Page_idPage`)
    REFERENCES `mydb`.`Page` (`idPage`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Options_Page2`
    FOREIGN KEY (`Page_idPageTarget`)
    REFERENCES `mydb`.`Page` (`idPage`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Parameter`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Parameter` (
  `idParameter` INT NOT NULL,
  `Name` VARCHAR(45) NOT NULL,
  `isText` TINYINT(1) NULL,
  `User_idUser` INT NOT NULL,
  `ScopeType` TINYINT(2) NOT NULL,
  `create_time` DATETIME NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`idParameter`),
  UNIQUE INDEX `Name_UNIQUE` (`Name` ASC) VISIBLE,
  INDEX `fk_Parameter_User1_idx` (`User_idUser` ASC) VISIBLE,
  CONSTRAINT `fk_Parameter_User1`
    FOREIGN KEY (`User_idUser`)
    REFERENCES `mydb`.`User` (`idUser`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Character`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Character` (
  `idCharacter` INT NOT NULL,
  `User_idUser` INT NOT NULL,
  `create_time` DATETIME NULL,
  PRIMARY KEY (`idCharacter`),
  INDEX `fk_Character_User1_idx` (`User_idUser` ASC) VISIBLE,
  CONSTRAINT `fk_Character_User1`
    FOREIGN KEY (`User_idUser`)
    REFERENCES `mydb`.`User` (`idUser`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`CPHistory`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`CPHistory` (
  `idUPHistory` INT NOT NULL,
  `create_time` DATETIME NULL DEFAULT CURRENT_TIMESTAMP,
  `ValueText` VARCHAR(45) NULL,
  `ValueNum` BIGINT NULL,
  PRIMARY KEY (`idUPHistory`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`CharacterParameter`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`CharacterParameter` (
  `idCharacterParameter` INT NOT NULL,
  `Character_idCharacter` INT NOT NULL,
  `Parameter_idParameter` INT NOT NULL,
  `ValueNum` BIGINT NULL,
  `ValueText` VARCHAR(45) NULL,
  `CPHistory_idUPHistory` INT NOT NULL,
  PRIMARY KEY (`idCharacterParameter`),
  INDEX `fk_CharacterParameter_Character1_idx` (`Character_idCharacter` ASC) VISIBLE,
  INDEX `fk_CharacterParameter_Parameter1_idx` (`Parameter_idParameter` ASC) VISIBLE,
  INDEX `fk_CharacterParameter_CPHistory1_idx` (`CPHistory_idUPHistory` ASC) VISIBLE,
  CONSTRAINT `fk_CharacterParameter_Character1`
    FOREIGN KEY (`Character_idCharacter`)
    REFERENCES `mydb`.`Character` (`idCharacter`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_CharacterParameter_Parameter1`
    FOREIGN KEY (`Parameter_idParameter`)
    REFERENCES `mydb`.`Parameter` (`idParameter`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_CharacterParameter_CPHistory1`
    FOREIGN KEY (`CPHistory_idUPHistory`)
    REFERENCES `mydb`.`CPHistory` (`idUPHistory`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`UPHistory`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`UPHistory` (
  `idUPHistory` INT NOT NULL,
  `create_time` DATETIME NULL DEFAULT CURRENT_TIMESTAMP,
  `ValueText` VARCHAR(45) NULL,
  `ValueNum` BIGINT NULL,
  PRIMARY KEY (`idUPHistory`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`UserParameter`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`UserParameter` (
  `idUserParameter` INT NOT NULL,
  `User_idUser` INT NOT NULL,
  `Parameter_idParameter` INT NOT NULL,
  `User_idUser1` INT NOT NULL,
  `ValueNum` BIGINT NULL,
  `ValueText` VARCHAR(45) NULL,
  `create_time` DATETIME NULL DEFAULT CURRENT_TIMESTAMP,
  `UPHistory_idUPHistory` INT NOT NULL,
  PRIMARY KEY (`idUserParameter`),
  INDEX `fk_UserParameter_User1_idx` (`User_idUser` ASC) VISIBLE,
  INDEX `fk_UserParameter_Parameter1_idx` (`Parameter_idParameter` ASC) VISIBLE,
  INDEX `fk_UserParameter_User2_idx` (`User_idUser1` ASC) VISIBLE,
  INDEX `fk_UserParameter_UPHistory1_idx` (`UPHistory_idUPHistory` ASC) VISIBLE,
  CONSTRAINT `fk_UserParameter_User1`
    FOREIGN KEY (`User_idUser`)
    REFERENCES `mydb`.`User` (`idUser`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_UserParameter_Parameter1`
    FOREIGN KEY (`Parameter_idParameter`)
    REFERENCES `mydb`.`Parameter` (`idParameter`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_UserParameter_User2`
    FOREIGN KEY (`User_idUser1`)
    REFERENCES `mydb`.`User` (`idUser`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_UserParameter_UPHistory1`
    FOREIGN KEY (`UPHistory_idUPHistory`)
    REFERENCES `mydb`.`UPHistory` (`idUPHistory`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Requirements`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Requirements` (
  `idRequirements` INT NOT NULL,
  `Parameter_idParameter` INT NOT NULL,
  `Options_idOptions` INT NOT NULL,
  PRIMARY KEY (`idRequirements`),
  INDEX `fk_Requirements_Parameter1_idx` (`Parameter_idParameter` ASC) VISIBLE,
  INDEX `fk_Requirements_Options1_idx` (`Options_idOptions` ASC) VISIBLE,
  CONSTRAINT `fk_Requirements_Parameter1`
    FOREIGN KEY (`Parameter_idParameter`)
    REFERENCES `mydb`.`Parameter` (`idParameter`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Requirements_Options1`
    FOREIGN KEY (`Options_idOptions`)
    REFERENCES `mydb`.`Options` (`idOptions`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`UPHistory_copy2`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`UPHistory_copy2` (
  `idUPHistory` INT NOT NULL,
  `create_time` DATETIME NULL DEFAULT CURRENT_TIMESTAMP,
  `ValueText` VARCHAR(45) NULL,
  `ValueNum` BIGINT NULL,
  PRIMARY KEY (`idUPHistory`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`GlobalParameter`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`GlobalParameter` (
  `idCharacterParameter` INT NOT NULL,
  `Parameter_idParameter` INT NOT NULL,
  `ValueNum` BIGINT NULL,
  `ValueText` VARCHAR(45) NULL,
  `UPHistory_copy2_idUPHistory` INT NOT NULL,
  PRIMARY KEY (`idCharacterParameter`),
  INDEX `fk_CharacterParameter_Parameter1_idx` (`Parameter_idParameter` ASC) VISIBLE,
  INDEX `fk_GlobalParameter_UPHistory_copy21_idx` (`UPHistory_copy2_idUPHistory` ASC) VISIBLE,
  CONSTRAINT `fk_CharacterParameter_Parameter10`
    FOREIGN KEY (`Parameter_idParameter`)
    REFERENCES `mydb`.`Parameter` (`idParameter`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_GlobalParameter_UPHistory_copy21`
    FOREIGN KEY (`UPHistory_copy2_idUPHistory`)
    REFERENCES `mydb`.`UPHistory_copy2` (`idUPHistory`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Permissions`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Permissions` (
  `User_idUser1` INT NOT NULL,
  PRIMARY KEY (`User_idUser1`),
  CONSTRAINT `fk_Permissions_User2`
    FOREIGN KEY (`User_idUser1`)
    REFERENCES `mydb`.`User` (`idUser`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

USE `mydb` ;

-- -----------------------------------------------------
-- Placeholder table for view `mydb`.`coautors`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`coautors` (`User_idUser` INT);

-- -----------------------------------------------------
-- View `mydb`.`coautors`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`coautors`;
USE `mydb`;
CREATE  OR REPLACE VIEW `coautors` AS

select
User_idUser
from PageTextHistory
Left join Page
on PageTextHistory.Page_idPage=Page.id_Page;

SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
